name: Debug Build

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare environment
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2

      - name: Install CQTDeployer
        run: sudo snap install cqtdeployer
      
      - name: Build
        run: |
          qmake OpenMic_Server.pro -config debug
          make
          /snap/cqtdeployer/current/cqtdeployer.sh -bin OpenMic_Server
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Linux_Release
          path: ./DistributionKit/
      
      - name: Generate installer
        run: |
          rm -rf ./DistributionKit
          /snap/cqtdeployer/current/cqtdeployer.sh -bin OpenMic_Server qif
      
      - name: Upload installer artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: OpenMic_Linux_Installer_amd64
          path: DistributionKit/InstallerOpenMic_Server.run
  
  build_windows:
    name: Windows Build
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare environment
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_msvc2019_64
          version: 5.15.2
      
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch_name }}
          qmake OpenMic_Server.pro -config debug
          nmake
          mkdir final_build
          copy debug\OpenMic_Server.exe final_build
          windeployqt ./final_build/OpenMic_Server.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Windows_Release_x64
          path: ./final_build/
      
      - name: Generate installer
        uses: joncloud/makensis-action@v3.4
        with:
          script-file: "windows_installer.nsi"

      - name: Upload installer artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Windows_Installer_${{ matrix.arch_name }}
          path: OpenMic_Windows_Installer_x64.exe
