name: Release Build

on:
  release:
    types: [published]

jobs:
  build_linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare environment
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2

      - name: Install CQTDeployer
        run: sudo snap install cqtdeployer
      
      - name: Build
        run: |
          qmake OpenMic_Server.pro -config release
          make
          /snap/cqtdeployer/current/cqtdeployer.sh -bin OpenMic_Server
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Linux_Release
          path: ./DistributionKit/
      
      - name: Prepare build for release
        run: |
          cd ./DistributionKit/
          zip -r OpenMic_Release.zip *
      
      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: DistributionKit/OpenMic_Release.zip
          asset_name: OpenMic_Linux_Portable_amd64.zip
          tag: ${{ github.ref }}
          overwrite: true
      
      - name: Generate installer
        run: |
          rm -rf ./DistributionKit
          /snap/cqtdeployer/current/cqtdeployer.sh -bin OpenMic_Server qif
        
      - name: Upload installer to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: DistributionKit/InstallerOpenMic_Server.run
          asset_name: OpenMic_Linux_Setup_amd64.run
          tag: ${{ github.ref }}
          overwrite: true
  
  build_windows:
    runs-on: windows-latest
    name: Windows Build
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare environment
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_msvc2019_64
          version: 5.15.2
      
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake OpenMic_Server.pro -config release
	  nmake
	  mkdir final_build
          copy release\OpenMic_Server.exe final_build
          windeployqt ./final_build/OpenMic_Server.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Windows_Release_x64
          path: ./final_build/

      - name: Prepare for release
        run: Compress-Archive final_build\* final_build.zip
      
      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: final_build.zip
          asset_name: OpenMic_Windows_Portable_x64.zip
          tag: ${{ github.ref }}
          overwrite: true
      
      - name: Generate installer
        uses: joncloud/makensis-action@v3.4
        with:
          script-file: "windows_installer.nsi"
      
      - name: Upload installer to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenMic_Windows_Installer.exe
          asset_name: OpenMic_Windows_Setup_x64.exe
          tag: ${{ github.ref }}
          overwrite: true
